# Local Database
spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=Mahak

# Local ML Service
ml.service.url=http://localhost:5000

# JWT
jwt.secret=expense_tracker_super_secret_key_2024